FROM node:16-alpine

USER node 

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./frontend/package.json ./package.json

RUN npm install 

COPY --chown=node:node ./frontend/ ./

CMD ["npm", "run", "start"]