# to make sure docker runs as root privelige 
sudo: required
services:
  - docker
before_install:
  - docker build -t azim31/react-fe -f frontend/Dockerfile .
script:
  - docker run -e CI=true zim31/react-fe npm run test

