# To make sure docker runs as root prevelige 

sudo: required
services:
  - docker
before_install:
  - docker build -t azim31/react-fe -f frontend/Dockerfile.dev .
script:
  - docker run -e CI=true azim31/react-fe npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-611812404044"
  bucket_path: "docker-react-app"
  on: 
    branch: main
  access_key_id: "$AWS_ACCESS_key"
  secret_access_key: "$AWS_SECRET_KEY"